services:
  #flask services
  flaskapp:
    container_name: flaskapp
    restart: always
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    environment:
      DB_USER: "${DB_USER}"
      DB_PASSWD: "${DB_PASSWD}"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: "${DB_NAME}"
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy 
        restart: true
  
  #db services
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 15s
      retries: 3

volumes:
  db-data: {} 

